services:
  mysql:
    image: mysql:8.0
    container_name: habit_tracker_mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database.sql:/docker-entrypoint-initdb.d/database.sql
    networks:
      - habit_tracker_network

  # Application Apache + PHP
  web:
    build: .
    container_name: habit_tracker_web
    restart: unless-stopped
    ports:
      - "8082:80"
    networks:
      - habit_tracker_network
    depends_on:
      - mysql
    environment:
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_DATABASE}
      - DB_USER=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}

volumes:
  mysql_data:

networks:
  habit_tracker_network:
    driver: bridge